In [3]:
import numpy as np
np.random.seed(0)
A = np.array([
[1, 1, 1, 1],
[1, 1, 0, 0],
[1, 0, 1, 1],
[1, 0, 1, 1]
])

In [5]:
connection = np.where(A > 0)

In [7]:
connection[0], connection[1]

(array([0, 0, 0, 0, 1, 1, 2, 2, 2, 3, 3, 3]),
 array([0, 1, 2, 3, 0, 1, 0, 2, 3, 0, 2, 3]))

In [8]:
c = np.random.rand(4,2)
c

array([[0.5488135 , 0.71518937],
       [0.60276338, 0.54488318],
       [0.4236548 , 0.64589411],
       [0.43758721, 0.891773  ]])

In [9]:
c[connection[0]]

array([[0.5488135 , 0.71518937],
       [0.5488135 , 0.71518937],
       [0.5488135 , 0.71518937],
       [0.5488135 , 0.71518937],
       [0.60276338, 0.54488318],
       [0.60276338, 0.54488318],
       [0.4236548 , 0.64589411],
       [0.4236548 , 0.64589411],
       [0.4236548 , 0.64589411],
       [0.43758721, 0.891773  ],
       [0.43758721, 0.891773  ],
       [0.43758721, 0.891773  ]])