In [1]:
import numpy as np
np.random.seed(0)

In [2]:
# ADJACENCY MATRIX
A = np.array([
    [1,1,1,1],
    [1,1,0,0],
    [1,0,1,1],
    [1,0,1,1]
])
A

array([[1, 1, 1, 1],
       [1, 1, 0, 0],
       [1, 0, 1, 1],
       [1, 0, 1, 1]])

In [3]:
# Node features, each row is a node
X = np.random.uniform(-1, 1, (4,4))
X

array([[ 0.09762701,  0.43037873,  0.20552675,  0.08976637],
       [-0.1526904 ,  0.29178823, -0.12482558,  0.783546  ],
       [ 0.92732552, -0.23311696,  0.58345008,  0.05778984],
       [ 0.13608912,  0.85119328, -0.85792788, -0.8257414 ]])

In [4]:
# Weight matrix
W = np.random.uniform(-1, 1, (2,4))

In [5]:
# Attention weight matrix
W_att = np.random.uniform(-1, 1, (1,2*2))

In [6]:
connection = np.where(A > 0)

In [9]:
a = W_att @ np.concatenate([(X @ W.T)[connection[0]], (X @ W.T)[connection[1]]], axis=1).T

In [11]:
def leaky_relu(x, alpha=0.2):
    return np.maximum(x, alpha*x)

e = leaky_relu(a)
e.shape

(1, 12)

In [12]:
E = np.zeros(A.shape)
E[connection[0], connection[1]] = e[0]
E

array([[-0.0201407 , -0.07188569,  0.96036209,  0.50390318],
       [-0.08791224, -0.13965724,  0.        ,  0.        ],
       [ 0.79964181,  0.        ,  1.8607074 ,  1.40424849],
       [ 0.64260322,  0.        ,  1.70366881,  1.2472099 ]])

In [13]:
def softmax(x, axis):
    return np.exp(x) / np.sum(np.exp(x), axis=axis)

W_alpha = softmax(E, axis=1)
W_alpha

array([[0.15862414, 0.24584279, 0.19034964, 0.13936964],
       [0.14823013, 0.22973368, 0.07285714, 0.08420266],
       [0.36007777, 0.26416607, 0.46834625, 0.34291239],
       [0.30774805, 0.26416607, 0.400282  , 0.2930773 ]])

In [14]:
H = A.T @ W_alpha @ X @ W.T

In [15]:
H

array([[-0.10961702,  1.89622018],
       [ 0.19504481,  0.59326539],
       [-0.25615163,  1.65534088],
       [-0.25615163,  1.65534088]])